const Database = require('better-sqlite3');
const db = new Database('server/data/freeapi.db');
console.log('=== fallback_config ===');
const fc = db.prepare('SELECT * FROM fallback_config').all();
console.log(JSON.stringify(fc, null, 2));
console.log('\n=== models (enabled) ===');
const models = db.prepare("SELECT id, model_id, platform, display_name, enabled FROM models WHERE enabled = 1 LIMIT 10").all();
console.log(JSON.stringify(models, null, 2));
console.log('\n=== keys ===');
const keys = db.prepare('SELECT * FROM keys').all();
console.log(JSON.stringify(keys, null, 2));
db.close();
