const Database = require('better-sqlite3');
const db = new Database('server/data/freeapi.db');
console.log('=== Custom/Zhipu models ===');
const models = db.prepare("SELECT id, model_id, platform, display_name, enabled FROM models WHERE platform IN ('custom','zhipu') ORDER BY platform, id").all();
console.log(JSON.stringify(models, null, 2));
console.log('\n=== Fusion settings ===');
const settings = db.prepare("SELECT * FROM settings WHERE key LIKE '%fusion%'").all();
console.log(JSON.stringify(settings, null, 2));
console.log('\n=== Total fallback_config with enabled=1 ===');
const fc = db.prepare('SELECT COUNT(*) as cnt FROM fallback_config WHERE enabled = 1').get();
console.log(JSON.stringify(fc));
const platforms = db.prepare("SELECT DISTINCT m.platform FROM fallback_config fc JOIN models m ON fc.model_db_id = m.id WHERE fc.enabled = 1").all();
console.log('Platforms in fallback:', platforms.map(p => p.platform).join(', '));
db.close();
